services:
  webserver:
    container_name: web-server
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - caddy-php-mysql-network
    depends_on:
      - mysql
      - php-fpm
    env_file:
      - "common/secrets.env"
    volumes:
      - ./webserver/src:/var/www/html/
      - ./webserver/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

  php-fpm:
    container_name: php-fpm
    build: ./webserver/
    command: sh -c "php /var/www/html/app/models/startup.php && exec php-fpm"
    env_file: 
      - "common/secrets.env"
    networks:
      - caddy-php-mysql-network
    volumes:
      - ./webserver/src:/var/www/html/

  mysql:
    image: mysql
    container_name: mysql-server
    env_file: 
      - "common/secrets.env"
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - caddy-php-mysql-network

networks:
  caddy-php-mysql-network:
    driver: bridge

volumes:
  mysql-volume:
  caddy_data:
